apiVersion: spec.keptn.sh/0.1.4
kind: Remediation
metadata:
  name: selobe-wind-remediation

spec:
  remediations:
    - problemType: number_of_errors
      actionsOnOpen:
        - name: Rollaback to previous version using helm
          action: rollback
          value: 
            stableVersion: "kuro08/selobe-wind:0.2.0"