apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-bird-app"
spec:
  stages:
    - name: "qcp"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
              triggeredAfter: "70s"
              properties:
                timeframe: "1m"

    - name: "mig"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "qcp.delivery.finished"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
              triggeredAfter: "70s"
              properties:
                timeframe: "1m"

    - name: "prd"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "mig.delivery.finished"
          tasks:
            - name: "approval"
              properties:
                pass: "automatic"
                warning: "manual"
            - name: "deployment"

        - name: "remediation"
          triggeredOn:
            - event: "prd.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "70s"
              properties:
                timeframe: "1m"