apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.deployment.triggered"
    tasks:
      - name: "Run helm"
        files:
          - /charts
        env:
          - name: IMAGE
            value: "$.data.configurationChange.values.image"
            valueFrom: event
        image: "alpine/helm:3.7.2"
        serviceAccount: "jes-deploy-using-helm"
        cmd:
          - "helm"
        args:
          - "upgrade"
          - "--create-namespace"
          - "--install"
          - "-n"
          - "$(KEPTN_PROJECT)-$(KEPTN_STAGE)"
          - "$(KEPTN_SERVICE)"
          - "/keptn/charts/$(KEPTN_SERVICE).tgz"
          - "--set"
          - "image=$(IMAGE)"
        ttlSecondsAfterFinished: 100

  - name: "Test the application"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run tests using python"
        files:
          - /tests
        serviceAccount: "jes-deploy-using-helm"
        image: "kuro08/python:latest"
        cmd: ["python"]
        args: ["/keptn/tests/tester.py"]
        ttlSecondsAfterFinished: 100
